db:
  image: mysql
  ports:
    - 3306:3306
  volumes:
    - ./mysql-data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

web:
  build: .
  command: "bash -c 'sleep 1 && go run main.go -config=config/dev.yaml'" # sleep to make sure DB is already running
  volumes:
    - .:/go/src/github.com/s-matyukevich/belarus-civil-rights-support
  ports:
    - 8080:8080
  links:
    - db

