db:
  image: mysql
  ports:
    - 3306:3306
  volumes:
    - ./mysql-data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

ui:
  build: .
  dockerfile: ./Dockerfile.ui
  command: "bash -c 'npm install && npm run start'"
  volumes:
    - ./client:/app
  ports:
    - 1234:1234

web:
  build: .
  dockerfile: ./Dockerfile.backend
  command: "bash -c 'sleep 1 && go run main.go -config=config/dev-secret.yaml'" # sleep to make sure DB is already running
  volumes:
    - .:/go/src/github.com/s-matyukevich/belarus-civil-rights-support
  ports:
    - 8080:8080
  links:
    - db
    - ui

