port: 8080
session_secret: very-secret # replace in prod
host: "http://localhost:8080"
ui_proxy_domain: "ui:1234"
allow_cors: false
preload_data: true

db:
  host: db
  database: maindb
  port: 3306
  username: root
  password: root

oauth:
  facebook:
    image: '/images/fb.png'
    client_id: '' # need to figure out a good way to share secrets like this in a public repo, for now I'll just use dev-secret.yaml to store the config with secrets and add it to gitignore. This file will be used as a template
    client_secret: ''
    auth_url: 'https://www.facebook.com/dialog/oauth'
    token_url: "https://graph.facebook.com/v2.6/oauth/access_token"
    scopes:
      - 'email'
  vk:
    image: 'images/vk.png'
    client_id: ''
    client_secret: ''
    auth_url: 'https://oauth.vk.com/authorize'
    token_url: 'https://oauth.vk.com/access_token'

data:
  categories: 
  - Нуждаюсь в финансовой доддержке
  - Ищу новую работу
  - Ищу единомышленников
  - Другое
  cities:
  - Барановичи
  - Барань
  - Белоозерск
  - Белыничи
  - Берёза
  - Березино
  - Березовка
  - Бобруйск
  - Борисов
  - Браслав
  - Брест
  - Буда-Кошелево
  - Быхов
  - Василевичи
  - Верхнедвинск
  - Ветка
  - Вилейка
  - Витебск
  - Волковыск
  - Воложин
  - Высокое
  - Ганцевичи
  - Глубокое
  - Гомель
  - Горки
  - Городок
  - Гродно
  - Давид-Городок
  - Дзержинск
  - Дисна
  - Добруш
  - Докшицы
  - Дрогичин
  - Дубровно
  - Дятлово
  - Ельск
  - Жабинка
  - Житковичи
  - Жлобин
  - Жодино
  - Заславль
  - Иваново
  - Ивацевичи
  - Ивье
  - Калинковичи
  - Каменец
  - Кировск
  - Клецк
  - Климовичи
  - Кличев
  - Кобрин
  - Копыль
  - Коссово
  - Костюковичи
  - Кричев
  - Круглое
  - Крупки
  - Лепель
  - Лида
  - Логойск
  - Лунинец
  - Любань
  - Ляховичи
  - Малорита
  - Марьина Горка	
  - Микашевичи
  - Минск
  - Миоры
  - Могилёв
  - Мозырь
  - Молодечно
  - Мосты
  - Мстиславль
  - Мядель
  - Наровля
  - Несвиж
  - Новогрудок
  - Новолукомль
  - Новополоцк
  - Орша
  - Осиповичи
  - Островец
  - Ошмяны
  - Петриков
  - Пинск
  - Полоцк
  - Поставы
  - Пружаны
  - Речица
  - Рогачёв
  - Светлогорск
  - Свислочь
  - Сенно
  - Скидель
  - Славгород
  - Слоним
  - Слуцк
  - Смолевичи
  - Сморгонь
  - Солигорск
  - Старые Дороги
  - Столбцы
  - Столин
  - Толочин
  - Туров
  - Узда
  - Фаниполь
  - Хойники
  - Чаусы
  - Чашники
  - Червень
  - Чериков
  - Чечерск
  - Шклов
  - Щучин