apiVersion: v1
kind: ConfigMap
metadata:
  name: dapamazhy-by
  namespace: {{ .Release.Namespace }}
  labels:
    app: dapamazhy-by
data:
  config.yaml: {{ toYaml .Values.config | indent 2 }}
  serviceAccount.json: {{ toYaml .Values.serviceAccount | indent 2 }}