apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapamazhy-by
  namespace: {{ $.Values.namespace }}
  labels:
    app: dapamazhy-by
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: 'dapamazhy-by'
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dapamazhy-by
    spec:
      containers:
      - name: main
        image: "{{ $.Values.image.image }}:{{ $.Values.image.tag }}"
        imagePullPolicy: Always
        command: ["/app/app"]
        args:
        - "-config=/etc/dapamazhy-by/config.yaml"
        volumeMounts:
        - name: config
          mountPath: /etc/dapamazhy-by
      volumes:
      - name: config
        configMap:
          name: dapamazhy-by