apiVersion: v1
kind: Service
metadata:
  name: dapamazhy-by
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: dapamazhy-by
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80